# .gitlab-ci.yml (top-level)

include:
  - local: /.gitlab/containerize.gitlab-ci.yml
  - local: /.gitlab/job-rules.gitlab-ci.yml
  - local: /.gitlab/container-scan.gitlab-ci.yml
  - local: /.gitlab/secrets.gitlab-ci.yml
  - local: /.gitlab/promote.gitlab-ci.yml
  - local: /.gitlab/release.gitlab-ci.yml

stages: [build, scan, render, promote, release]

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

# Global defaults (inherited by all jobs unless overridden)
default:
  interruptible: true

variables:
  PUSH_FEATURE_BRANCH: "false"

