include:
  - local: '.ci-templates/docker.gitlab-ci.yml'
  - local: '.ci-templates/secrets-analyzer.gitlab-ci.yml'

stages:
  - build
  - scan
  - release

# -----------------------------------------------------------
# Feature branch build
# -----------------------------------------------------------
build_feature:
  stage: build
  extends: [".build-common"]
  variables:
    IMAGE_ENV_PATH: "$CI_REGISTRY_IMAGE/app"  # e.g., registry.example.com/group/project/app
    RELEASE_IMAGE: "false"   # CRITICAL: Never push feature builds
    TAG_SUFFIX: ""           # No suffix for feature branches
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^gmarm-/

# ---------------------------
# Build & push for dev branch
# ---------------------------
build_dev:
  stage: build
  extends: .build-common
  variables:
    # override per-service as needed
    IMAGE_ENV_PATH: "$CI_REGISTRY_IMAGE/python"
    TAG_SUFFIX: "dev"        # dev-a1b2c3d
    PUSH_IMAGE: "true"       # push so dev cluster can pull it
    TAG_LATEST: "false"      # don't pollute :latest
    RELEASE_IMAGE: "false"
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  # image-digest.env is already exported by .build-common as dotenv + artifact