include:
  # Reference your local build-common template
  local: '.ci-templates/docker.gitlab-ci.yml'

stages:
  - build
  - release

# -----------------------------------------------------------
# Feature branch build (build only, no push)
# -----------------------------------------------------------
build_feature:
  stage: build
  extends: [".build-common"]
  variables:
    DOCKER_CONTEXT: "."                           # Dockerfile at root
    IMAGE_ENV_PATH: $CI_REGISTRY_IMAGE/python
    DOCKERFILE: Dockerfile
    TAG_MODE: static                       # Use commit SHA or tag
    TAG_SUFFIX: "3.12"
    PUSH_IMAGE: "true"                       # Feature branch = build only
    TAG_LATEST: "true"
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "dev"'