include:
  - local: '.gitlab/job-rules.gitlab-ci.yml'
  - local: '.gitlab/secrets.gitlab-ci.yml'
  - local: '.gitlab/container-scan.gitlab-ci.yml'
  - local: '.gitlab/docker.gitlab-ci.yml'
  - local: '.gitlab/deploy.gitlab-ci.yml'
  - local: '.gitlab/release.gitlab-ci.yml'


stages: [build, scan, deploy, release]



variables:
  APP_NAME: templates
  PUSH_ON_FEATURE: "true"


# ---------------------------
# Build
# ---------------------------
build:docker:
  stage: build
  interruptible: true
  extends: .build-common
  rules: !reference [.rule:build-simple, rules]

debug:dotenv:
  stage: scan
  needs:
    - job: build:docker      # <<< again, MUST be the real name
      artifacts: true
  script:
    - echo "Should see IMAGE_* from dotenv below:"
    - env | sort | grep -E '^(IMAGE_|CS_IMAGE=)' || true
