include:
  - local: '.ci-templates/docker.gitlab-ci.yml'
  - local: '.ci-templates/secrets-analyzer.gitlab-ci.yml'

stages:
  - build
  - scan
  - release

# -----------------------------------------------------------
# Feature branch build
# -----------------------------------------------------------
build_feature:
  stage: build
  extends: [".build-common"]
  variables:
    DOCKER_CONTEXT: "."
    IMAGE_ENV_PATH: $CI_REGISTRY_IMAGE/python
    DOCKERFILE: Dockerfile
    TAG_MODE: static
    TAG_SUFFIX: "3.12"
    PUSH_IMAGE: "false"
    TAG_LATEST: "false"
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "dev"'

