include:
  - local: '.ci-templates/docker.gitlab-ci.yml'
  - local: '.ci-templates/secrets-analyzer.gitlab-ci.yml'

stages:
  - scan
  - build
  - release

# -----------------------------------------------------------
# Feature branch build
# -----------------------------------------------------------
build_feature:
  stage: build
  extends: [".build-common"]
  variables:
    DOCKER_CONTEXT: "."
    IMAGE_ENV_PATH: $CI_REGISTRY_IMAGE/python
    DOCKERFILE: Dockerfile
    TAG_MODE: static
    TAG_SUFFIX: "3.12"
    PUSH_IMAGE: "true"
    TAG_LATEST: "true"
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "dev"'

# -----------------------------------------------------------
# Grype scan after image build
# -----------------------------------------------------------
grype_scan:
  services:
    - name: docker:24.0.5-dind
      alias: docker
  stage: scan
  image: anchore/grype
  script:
    - |
      grype nginx --only-fixed