# -------------------------------------------------------------------
# Example CI Pipeline
# -------------------------------------------------------------------
include:
  - local: '.gitlab/job-rules.gitlab-ci.yml'     # ➊ rules first
  - local: '.gitlab/secrets.gitlab-ci.yml'       # scans can !reference rules now
  - local: '.gitlab/docker.gitlab-ci.yml'
  - local: '.gitlab/deploy.gitlab-ci.yml'
  - local: '.gitlab/release.gitlab-ci.yml'

stages: [verify, build, scan, deploy, release]

variables:
  APP_NAME: templates

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

# ---------------------------
# Build
# ---------------------------
build:docker:
  stage: build
  interruptible: true
  extends: .build-common
  rules: !reference [.rule:build-matrix, rules]






