# -------------------------------------------------------------------
# Example CI Pipeline
# -------------------------------------------------------------------
include:
  - local: '.gitlab/job-rules.gitlab-ci.yml'     # ➊ rules first
  - local: '.gitlab/secrets.gitlab-ci.yml'       # scans can !reference rules now
  - local: '.gitlab/docker.gitlab-ci.yml'
  - local: '.gitlab/deploy.gitlab-ci.yml'
  - local: '.gitlab/release.gitlab-ci.yml'

stages: [verify, build, scan, deploy, release]

variables:
  APP_NAME: templates
  DEV_TAG_SUFFIX: "dev"
  TEST_TAG_SUFFIX: "test"
  INT_TAG_SUFFIX:  "int"
  PROD_TAG_SUFFIX: "prod"
  MR_TAG_SUFFIX:   "mr"
  FEATURE_TAG_SUFFIX: "feat"
  PUSH_ON_FEATURE: "false"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

# ---------------------------
# Build
# ---------------------------
build:
  stage: build
  interruptible: true
  extends: .build-common

  rules:
    # 1) gmarm-* branch PUSH pipelines
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null && $CI_COMMIT_BRANCH =~ /^gmarm-/'
      variables:
        PUSH_IMAGE: "$PUSH_ON_FEATURE"   # likely "false" by default
        TAG_SUFFIX: "$FEATURE_TAG_SUFFIX"

    # 2) gmarm-* MR pipelines (source branch is gmarm-*)
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^gmarm-/'
      variables:
        PUSH_IMAGE: "false"
        TAG_SUFFIX: "$MR_TAG_SUFFIX"

    # 3) tags → release behavior
    - if: '$CI_COMMIT_TAG'
      variables:
        RELEASE_IMAGE: "true"
        PUSH_IMAGE: "true"
        TAG_SUFFIX: ""
        TAG_LATEST: "false"

    # 4) env branches
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "prod"'
      variables: { PUSH_IMAGE: "true", TAG_SUFFIX: "$PROD_TAG_SUFFIX", TAG_LATEST: "true" }
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "int"'
      variables: { PUSH_IMAGE: "true", TAG_SUFFIX: "$INT_TAG_SUFFIX" }
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "test"'
      variables: { PUSH_IMAGE: "true", TAG_SUFFIX: "$TEST_TAG_SUFFIX" }
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
      variables: { PUSH_IMAGE: "true", TAG_SUFFIX: "$DEV_TAG_SUFFIX" }

    # 5) deny the rest
    - when: never

