include:
  - local: '.ci-templates/docker.gitlab-ci.yml'
  - local: '.ci-templates/secrets-analyzer.gitlab-ci.yml'

stages:
  - build
  - scan
  - release

# -----------------------------------------------------------
# Feature branch build
# -----------------------------------------------------------
build_feature:
  stage: build
  extends: [".build-common"]
  variables:
    DOCKER_CONTEXT: "."
    IMAGE_ENV_PATH: $CI_REGISTRY_IMAGE/python
    DOCKERFILE: Dockerfile
    TAG_MODE: static
    TAG_SUFFIX: "3.12"
    PUSH_IMAGE: "true"
    TAG_LATEST: "true"
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "dev"'

# -------------------------------------------------------------------
# Grype Echo Digest Template
#
# Just prints out the digest saved by `.build-common`.
# Useful for debugging or dry-run scanning logic.
# -------------------------------------------------------------------

grype_echo_template:
  stage: scan
  image: alpine:latest
  dependencies: ["build_feature"]
  script:
    - |
      if [ ! -f image-digest.env ]; then
        echo "❌ image-digest.env not found"
        exit 1
      fi

      source image-digest.env

      if [ "${IMAGE_DIGEST}" = "skipped" ]; then
        echo "⚠️ No image digest (build did not push)"
      else
        echo "✅ Image digest found: $IMAGE_DIGEST"
      fi