include:
  - local: '.ci-templates/docker.gitlab-ci.yml'
  - local: '.ci-templates/secrets-analyzer.gitlab-ci.yml'

stages:
  - build
  - scan
  - release

# -----------------------------------------------------------
# Feature branch build
# -----------------------------------------------------------
build_feature:
  stage: build
  extends: [".build-common"]
  variables:
    DOCKER_CONTEXT: "."
    IMAGE_ENV_PATH: $CI_REGISTRY_IMAGE/python
    DOCKERFILE: Dockerfile
    TAG_MODE: static
    TAG_SUFFIX: "3.12"
    PUSH_IMAGE: "false"
    TAG_LATEST: "false"
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "dev"'

# -------------------------------------------------------------------
# Grype Echo Digest Template
#
# Just prints out the digest saved by `.build-common`.
# Useful for debugging or dry-run scanning logic.
# -------------------------------------------------------------------

grype_echo_template:
  stage: scan
  image: alpine:3.20
  needs:
    - job: build_feature
      artifacts: true
  dependencies: ["build_feature"]
  variables:
    GIT_STRATEGY: none
  script:
    - set -euo pipefail
    - |
      # Prefer dotenv-injected env; if not present, source the file.
      if [ -z "${IMAGE_REF:-}" ] && [ -z "${IMAGE_DIGEST:-}" ]; then
        if [ ! -f image-digest.env ]; then
          echo "❌ image-digest.env not found and no env vars present"
          exit 1
        fi
        set -a; . image-digest.env; set +a
      fi

      # Handle no-push case
      if { [ "${IMAGE_REF:-skipped}" = "skipped" ] && [ "${IMAGE_DIGEST:-skipped}" = "skipped" ]; }; then
        echo "⚠️ No pushed image (skipped)"; exit 0
      fi

      # Echo everything useful
      [ -n "${IMAGE_REF:-}" ]     && [ "${IMAGE_REF}"     != "skipped" ] && echo "✅ IMAGE_REF: ${IMAGE_REF}"
      [ -n "${IMAGE_ENV_PATH:-}" ]                                    && echo "  IMAGE_ENV_PATH: ${IMAGE_ENV_PATH}"
      [ -n "${IMAGE_TAG:-}" ]                                         && echo "  IMAGE_TAG: ${IMAGE_TAG}"
      [ -n "${IMAGE_DIGEST:-}" ] && [ "${IMAGE_DIGEST}" != "skipped" ] && echo "✅ IMAGE_DIGEST: ${IMAGE_DIGEST}"