


variables:
  APP_NAME: syac-test
  PUSH_ON_FEATURE: "true"
  # Tell syac the app name (fallback is last segment of CI_REGISTRY_IMAGE)
  SYAC_APPLICATION_NAME: "$APP_NAME"
  # Gate feature-branch pushes (syac reads PUSH_FEATURE)
  PUSH_FEATURE: "$PUSH_ON_FEATURE"
  SYAC_LATEST_ON_FEATURE: "true"


stages:
  - build


syac:build:
  stage: build
  image: registry.simulogix.com/personal-websites/syac-3.0/syac:latest
  services:
    - name: docker:24-dind
      command: ["--mtu=1460"]
  script:
    - mkdir -p artifacts
    - ./syac
  artifacts:
    when: always
    paths:
      - artifacts/syac.env
    expire_in: 1 week
