include:
  - local: '.gitlab/job-rules.gitlab-ci.yml'
  - local: '.gitlab/secrets.gitlab-ci.yml'
  - local: '.gitlab/container-scan.gitlab-ci.yml'
  - local: '.gitlab/docker.gitlab-ci.yml'
  - local: '.gitlab/deploy.gitlab-ci.yml'
  - local: '.gitlab/release.gitlab-ci.yml'


stages: [debug, build, scan, deploy, release]



variables:
  APP_NAME: templates
  PUSH_ON_FEATURE: "false"


debug:environment:
  stage: debug
  image: alpine:3.20
  script:
    - echo "Dumping all CI_ environment variables..."
    - printenv | sort



# ---------------------------
# Build
# ---------------------------
build:docker:
  stage: build
  interruptible: true
  extends: .build_image_template
  rules: !reference [.rule:build-simple, rules]


