include:
  - local: '.ci-templates/docker.gitlab-ci.yml'
  - local: '.ci-templates/secrets-analyzer.gitlab-ci.yml'

stages:
  - build
  - scan
  - release

# -----------------------------------------------------------
# Feature branch build
# -----------------------------------------------------------
build_feature:
  stage: build
  extends: [".build-common"]
  variables:
    IMAGE_ENV_PATH: "$CI_REGISTRY_IMAGE/app"  # e.g., registry.example.com/group/project/app
    RELEASE_IMAGE: "false"   # CRITICAL: Never push feature builds
    TAG_SUFFIX: ""           # No suffix for feature branches
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^gmarm-/
  script:
    - echo "Building feature branch $CI_COMMIT_BRANCH (no push)"
    # The template handles everything else automatically

