# .gitlab-ci.yml

include:
  - local: /.gitlab/docker.gitlab-ci.yml
  - local: /.gitlab/job-rules.gitlab-ci.yml
  - local: /.gitlab/container-scan.gitlab-ci.yml

stages:
  - build
  - scan

# This is the main build job for your container.
# It uses the .build_image_template for the logic
# and .rule:build-simple for the rules.
build:docker:
  stage: build
  extends: .build_image_template
  # You can set container-specific variables here
  variables:
    APP_NAME: "my-awesome-app" # Change this for each of your 60+ containers
    # PUSH_ON_FEATURE: "true" # Uncomment to push images for feature branches
  rules: !reference [.rule:build-simple, rules]

# The scan:container job is included from container-scan.gitlab-ci.yml.
# It will automatically run after build:docker on merge requests,
# as defined by the .rule:scan-on-mr-to-env rule.
#
# If you wanted to scan on every merge request, you could override the rule like this:
#
# scan:container:
#   rules: !reference [.rule:mr-only, rules]