


variables:
  APP_NAME: syac-test
  PUSH_ON_FEATURE: "true"
  # Tell syac the app name (fallback is last segment of CI_REGISTRY_IMAGE)
  SYAC_APPLICATION_NAME: "$APP_NAME"
  # Gate feature-branch pushes (syac reads PUSH_FEATURE)
  PUSH_FEATURE: "$PUSH_ON_FEATURE"
  SYAC_LATEST_ON_FEATURE: "true"


stages:
  - build


syac:build:
  stage: build
  image: registry.simulogix.com/personal-websites/syac-3.0/syac:latest
  services:
    - name: docker:24-dind
      command: ["--mtu=1460"]

  before_script:
  - set -euo pipefail
  - echo "Login $CI_REGISTRY as $CI_REGISTRY_USER"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  script:
    - mkdir -p artifacts
    - ./syac
  artifacts:
    when: always
    paths:
      - artifacts/syac.env
    expire_in: 1 week
