# .gitlab-ci.yml (top-level)

include:
  - local: /.gitlab/containerize-dependency.gitlab-ci.yml
  # - local: /.gitlab/containerize.gitlab-ci.yml
  - local: /.gitlab/job-rules.gitlab-ci.yml
  - local: /.gitlab/container-scan.gitlab-ci.yml
  # - local: /.gitlab/secrets.gitlab-ci.yml


stages: [build, scan]


# Global defaults (inherited by all jobs unless overridden)
default:
  interruptible: true

variables:
  PUSH_LATEST: "false"
  CI_APPLICATION_TAG: 3.3.0
  EXTRA_BUILD_ARGS: "NPM_TOKEN=zack SOME_FLAG=true"


