gitlab_release:
  stage: release
  image:
    name: registry.gitlab.com/gitlab-org/release-cli:0.21.0
    entrypoint: [""]
  rules:
    - if: '$GITLAB_RELEASE_DISABLED =~ /(?i)true/'
      when: never
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never
  variables:
    RELEASE_NOTES_FILE: "release_notes.md"
  before_script:
    - set -euo pipefail
    - |
      if [ -z "${SPRINT:-}" ]; then
        echo "ERROR: Missing required variable SPRINT."
        echo "Set it at the pipeline level or in the trigger (e.g., variables: { SPRINT: 125 })."
        exit 1
      fi
    - export RELEASE_NAME="Version ${CI_COMMIT_TAG} Release - Sprint ${SPRINT}"
    - |
      if [ -f CHANGELOG.md ]; then
        awk 'BEGIN{p=0} /^## /{if(p) exit; p=1} p' CHANGELOG.md > "$RELEASE_NOTES_FILE" || true
      fi
      [ -s "$RELEASE_NOTES_FILE" ] || printf "Created by CI for %s (%s)\n" "$CI_COMMIT_TAG" "$CI_COMMIT_SHA" > "$RELEASE_NOTES_FILE"
  script:
    - |
      if release-cli list | grep -qx "$CI_COMMIT_TAG"; then
        release-cli update \
          --name "$RELEASE_NAME" \
          --tag-name "$CI_COMMIT_TAG" \
          --description "$RELEASE_NOTES_FILE"
      else
        release-cli create \
          --name "$RELEASE_NAME" \
          --tag-name "$CI_COMMIT_TAG" \
          --ref "$CI_COMMIT_SHA" \
          --description "$RELEASE_NOTES_FILE"
      fi
  retry:
    max: 1
    when: [api_failure, runner_system_failure, unknown_failure]
  allow_failure: false