# -------------------------------------------------------------------
# Run scans only when an MR targets env branches
# -------------------------------------------------------------------
.rule:scan-on-mr-to-env:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(dev|test|int|prod|main|master)$/'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:scan-manual-non-mr:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual
      allow_failure: true

# -------------------------------------------------------------------
.rule:push-or-mr:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:push-branches-only:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:tag-only:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:mr-only:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:manual-anywhere:
  rules:
    - when: manual
      allow_failure: false

# -------------------------------------------------------------------
.rule:default-branch-only:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:protected-branches-only:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:protected-tags-only:
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:env-branches-only:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(dev|test|int|prod|main|master)$/'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:schedule-only:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
    - when: never

# -------------------------------------------------------------------
.rule:rc-tags-only:
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$/'
      when: on_success
    - when: never

# -------------------------------------------------------------------
# Scans should run on dev merges and on release tags
# -------------------------------------------------------------------
.rule:scan-dev-or-tag:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
      when: on_success
    - when: never


# -------------------------------------------------------------------
# Scan on MRs automatically; allow manual on default or gmarm-* branches
# -------------------------------------------------------------------
.rule:scan-on-mr-or-manual:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^gmarm-[A-Za-z0-9._-]+$/'
      when: manual
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
      allow_failure: true
    - when: never

# -------------------------------------------------------------------
.rule:scheduled-nightly:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success

# -------------------------------------------------------------------
.rule:sast_scan:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^gmarm-[A-Za-z0-9._-]+$/'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual