# This pipeline is responsible for creating a GitLab Release.
# It should be triggered by a parent pipeline on tag creation.

stages:
  - release

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    # Ensure this job only runs when triggered by a parent pipeline on a tag.
    - if: '$CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "parent_pipeline"'
  script:
    - echo "Creating release for tag $CI_COMMIT_TAG"
    - |
      release-cli create \
        --name "Release ${CI_COMMIT_TAG}" \
        --tag-name "${CI_COMMIT_TAG}" \

