# security/grype.yml
.container-scan-template:
  stage: scan
  image: alpine:3.20
  needs:
    - job: build:docker
      artifacts: true
  allow_failure: true
  rules: !reference [.rule:scan-on-mr-to-env, rules]

  before_script:
    - set -euo pipefail
    - |
      if [ ! -f image-digest.env ]; then
        echo "❌ No image-digest.env found — skipping scan"
        exit 0
      fi
      source image-digest.env
      if [ -z "${IMAGE_REF:-}" ] || [ "${IMAGE_REF}" = "skipped" ]; then
        echo "❌ No valid IMAGE_REF found — skipping scan"
        exit 0
      fi
      echo "✅ Found IMAGE_REF=${IMAGE_REF}, starting scan..."

