include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

# Your wrapped job
scan:container-scanning:
  extends: container_scanning
  stage: scan                      # <-- override stage from "test" to "scan"
  needs:
    - job: build:docker
      artifacts: true
      optional: true
  allow_failure: true
  rules: !reference [.rule:scan-when-image-exists, rules]

  before_script:
    - set -euo pipefail 2>/dev/null || set -eu
    - |
      if [ ! -f image-digest.env ]; then
        echo "No image-digest.env — skipping"; exit 0
      fi
      . image-digest.env
      if [ -z "${IMAGE_REF:-}" ] || [ "${IMAGE_REF}" = "skipped" ]; then
        echo "No IMAGE_REF (image not pushed) — skipping"; exit 0
      fi
      echo "Scanning ${IMAGE_REF} ..."
      export CS_IMAGE="${IMAGE_REF}"

  variables:
    DOCKER_AUTH_CONFIG: >
      {"auths":{
        "${CI_REGISTRY}":{"username":"${CI_REGISTRY_USER}","password":"${CI_REGISTRY_PASSWORD}"}
      }}
    # CS_SEVERITY_THRESHOLD: "critical"
    # CS_DISABLE_LANGUAGE_VULNERABILITY_SCAN: "true"
