# ----------------------------
# Container Scanning (digest-aware, dotenv-driven)
# ----------------------------
#
# This pipeline template provides a security-focused container scanning workflow for GitLab CI/CD.
# Key features:
#   - Digest-aware scanning (uses precise image digests for accurate vulnerability detection)
#   - dotenv-driven configuration (pulls environment variables from .env files)
#   - Integrates with GitLab's security scanning tools (Container Scanning, SBOM)
#   - Optional dependency on build jobs (supports scanning without full build pipeline)
#   - Configurable severity thresholds and scan rules
#
# Usage:
# 1. Place this template in your .gitlab-ci.yml file
# 2. Ensure your build job (e.g., build:docker) produces an IMAGE_REF variable
# 3. Configure security scanners and credentials in your .env file
# 4. Customize scan rules and thresholds as needed


variables:
  CS_ANALYZER_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/security-products/container-scanning:8"
  CS_SCHEMA_MODEL: 15

scan:container:
  image: "$CS_ANALYZER_IMAGE$CS_IMAGE_SUFFIX"
  stage: scan
  needs:
    - job: build:docker
      artifacts: true
      optional: true
  allow_failure: true
  variables:
    GIT_STRATEGY: none
    CS_REGISTRY: "$CI_REGISTRY"
    CS_REGISTRY_USER: "$CI_REGISTRY_USER"
    CS_REGISTRY_PASSWORD: "$CI_JOB_TOKEN"
    CS_SCHEMA_MODEL: 15
  before_script:
    - set -euo pipefail 2>/dev/null || set -eu
    - |
      if [ -z "${IMAGE_REF:-}" ] || [ "${IMAGE_REF}" = "skipped" ]; then
        echo "No IMAGE_REF — exit 0"; exit 0
      fi
      export CS_IMAGE="${IMAGE_REF}"
      echo "Scanning ${CS_IMAGE}"
  script:
    - gtcs scan
  rules: !reference [.rule:scan-on-mr-or-manual, rules]
  artifacts:
    access: developer
    reports:
      container_scanning: gl-container-scanning-report.json
      cyclonedx: "**/gl-sbom-*.cdx.json"
    paths:
      - gl-container-scanning-report.json
      - gl-dependency-scanning-report.json
      - "**/gl-sbom-*.cdx.json"


