variables:
  CS_ANALYZER_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/security-products/container-scanning:8"
  CS_SCHEMA_MODEL: 15

scan:container:
  image: "$CS_ANALYZER_IMAGE$CS_IMAGE_SUFFIX"
  stage: scan
  needs:
    - job: build:docker
      artifacts: true
      optional: true
  allow_failure: true
  variables:
    GIT_STRATEGY: none
    CS_REGISTRY: "$CI_REGISTRY"
    CS_REGISTRY_USER: "$CI_REGISTRY_USER"
    CS_REGISTRY_PASSWORD: "$CI_JOB_TOKEN"
    CS_SCHEMA_MODEL: 15
    # CS_SEVERITY_THRESHOLD: "low"
  before_script:
    - set -euo pipefail 2>/dev/null || set -eu
    - |
      if [ -z "${IMAGE_REF:-}" ] || [ "${IMAGE_REF}" = "skipped" ]; then
        echo "No IMAGE_REF — exit 0"; exit 0
      fi
      export CS_IMAGE="${IMAGE_REF}"
      export DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME}"
      echo "Full Image Path to be scanned ${DOCKER_IMAGE_NAME}"
      echo "Scanning Image using Digest ${CS_IMAGE}"
  script:
    - gtcs scan
  rules: !reference [.rule:scan-on-mr-or-manual, rules]
  artifacts:
    access: developer
    reports:
      container_scanning: gl-container-scanning-report.json
      cyclonedx: "**/gl-sbom-*.cdx.json"
    paths:
      - gl-container-scanning-report.json
      - "**/gl-sbom-*.cdx.json"


