# .gitlab/job-rules.gitlab-ci.yml
# Reusable rules — hidden jobs you can !reference from any job's `rules:`.
# First match wins. End with an explicit deny where appropriate.

# --- MR targets: env branches (your original) ---
.rule:scan-on-mr-to-env:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(dev|test|int|main)$/'
      when: on_success
    - when: never

# --- Manual only on non-MR pipelines (your original) ---
.rule:scan-manual-non-mr:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual
      allow_failure: false

# --- Generic, often-needed blocks ---
# Push or MR only (deny schedules/web/API unless explicitly allowed)
.rule:push-or-mr:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never

# Branch pushes only (exclude tag pipelines and MRs)
.rule:push-branches-only:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null'
      when: on_success
    - when: never

# Tag pipelines only
.rule:tag-only:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never

# MR pipelines only (any target branch)
.rule:mr-only:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never

# Manual button everywhere (always visible, never auto-run)
.rule:manual-anywhere:
  rules:
    - when: manual
      allow_failure: false