# .gitlab/job-rules.gitlab-ci.yml
#
# Reusable job rules — each block is a hidden job that can be referenced
# with:
#   rules: !reference [.rule:name-here, rules]
#
# NOTES:
# - "First match wins": GitLab evaluates rules top-to-bottom and stops on the first match.
# - Always end with an explicit `- when: never` to deny all non-matching cases.
# - Use these to avoid copy/pasting complex `if:` conditions across jobs.

# -------------------------------------------------------------------
# Run automatically on merge request pipelines targeting specific env
# branches (dev, test, int, main). Denies all other branches/pipeline types.
# Useful for scan jobs you only want before merging into critical branches.
# -------------------------------------------------------------------
.rule:scan-on-mr-to-env:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(dev|test|int|main|master)$/'
      when: on_success
    - when: never

# -------------------------------------------------------------------
# Manual button ONLY on non-MR pipelines.
# Hides the job entirely in MR pipelines, shows as a manual action elsewhere.
# `allow_failure: true` makes it optional so earlier stages won't block.
# Use for on-demand scans in push/tag pipelines without blocking the build.
# -------------------------------------------------------------------
.rule:scan-manual-non-mr:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual
      allow_failure: true

# -------------------------------------------------------------------
# Allow job to run only on push or MR pipelines (exclude schedules, web/API).
# Good default gate when you only want code-triggered pipelines to run the job.
# -------------------------------------------------------------------
.rule:push-or-mr:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never

# -------------------------------------------------------------------
# Allow only branch pushes (no MRs, no tag pipelines).
# Useful for jobs that should run only when code is pushed to a branch directly.
# -------------------------------------------------------------------
.rule:push-branches-only:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null'
      when: on_success
    - when: never

# -------------------------------------------------------------------
# Allow only tag pipelines.
# Common for release jobs that should run when a version tag is pushed.
# -------------------------------------------------------------------
.rule:tag-only:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never

# -------------------------------------------------------------------
# Allow only merge request pipelines, regardless of target branch.
# Use for MR-wide scanning/testing that runs before any merge.
# -------------------------------------------------------------------
.rule:mr-only:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never

# -------------------------------------------------------------------
# Always show a manual button, regardless of pipeline type.
# Never auto-runs; `allow_failure: false` means clicking "Play" must succeed
# for the pipeline to pass.
# -------------------------------------------------------------------
.rule:manual-anywhere:
  rules:
    - when: manual
      allow_failure: false