# .gitlab/job-rules.gitlab-ci.yml
.rule:scan-on-mr-to-env:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(dev|test|int|main)$/'
      when: on_success
    - when: never

.rule:scan-manual:
  rules:
    - when: manual
      allow_failure: true