.promote:
  image: docker:cli
  stage: promote
  services:
    - docker:dind
  variables:
    GIT_STRATEGY: none
    DOCKER_TLS_CERTDIR: ""
    ALLOWED_ENVS: "dev int prod staging"
  needs:
    - job: build:docker
      artifacts: true
  before_script:
    - set -euo pipefail
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin "$CI_REGISTRY"
    - |
      if [ -z "${IMAGE_REF:-}" ]; then
        echo "ERROR: IMAGE_REF missing from build:docker dotenv"; exit 1
      fi
      if [ -z "${CI_COMMIT_TAG:-}" ]; then
        echo "ERROR: Promotion only allowed on tag pipelines"; exit 1
      fi
      if [ -z "${TARGET_ENV:-}" ]; then
        echo "ERROR: TARGET_ENV must be set"; exit 1
      fi
      case " ${ALLOWED_ENVS} " in
        *" ${TARGET_ENV} "*) : ;;
        *) echo "ERROR: TARGET_ENV='${TARGET_ENV}' not allowed (${ALLOWED_ENVS})"; exit 1;;
      esac
    - docker pull "${IMAGE_REF}"
    - SRC_REPO="${IMAGE_REF%@*}"
    - TGT_VER="${SRC_REPO}:${TARGET_ENV}-${CI_COMMIT_TAG}"
    - SRC_ID="$(docker image inspect --format='{{.Id}}' "${IMAGE_REF}")"
    - |
      if [ -z "${SRC_ID}" ]; then
        echo "ERROR: could not resolve local image ID for ${IMAGE_REF}"; exit 1
      fi
  script:
    - set -euo pipefail
    - docker tag "${SRC_ID}" "${TGT_VER}"
    - docker push "${TGT_VER}"
    - docker pull "${TGT_VER}"
    - PUBLISHED_DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' "${TGT_VER}" | cut -d'@' -f2)"
    - |
      if [ -z "${PUBLISHED_DIGEST}" ]; then
        echo "ERROR: failed to resolve pushed digest"; exit 1
      fi
    - TARGET_ENV_UPPER="$(echo "$TARGET_ENV" | tr '[:lower:]' '[:upper:]')"
    - |
      {
        echo "${TARGET_ENV_UPPER}_IMAGE_REF=${SRC_REPO}@${PUBLISHED_DIGEST}"
        echo "${TARGET_ENV_UPPER}_IMAGE_TAG_VER=${TGT_VER}"
      } > promote.env
  artifacts:
    reports:
      dotenv: promote.env
    paths:
      - promote.env
    expire_in: 7 days
  rules:
    - if: '$CI_COMMIT_TAG'
  after_script:
    - docker logout "$CI_REGISTRY" || true

promote:dev:
  extends: .promote
  variables:
    TARGET_ENV: dev
  environment:
    name: dev
    url: https://dev.zb.openshift.com
    action: start
  resource_group: "$CI_PROJECT_PATH:promote-dev"
