stages:
  - release

release:dev:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:v0.18.0
  needs:
    - job: promote:dev
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG'
  retry: { max: 0 }
  before_script:
    - set -euo pipefail
    - release-cli --version
    - source promote.env
  script:
    - |
      NOTES="Release ${CI_COMMIT_TAG} — promoted to dev"
      release-cli create \
        --name "Release ${CI_COMMIT_TAG}" \
        --tag-name "${CI_COMMIT_TAG}" \
        --description "${NOTES}" || \
      release-cli update \
        --name "Release ${CI_COMMIT_TAG}" \
        --tag-name "${CI_COMMIT_TAG}" \
        --description "${NOTES}"
