# .gitlab/secrets.gitlab-ci.yml
# include:
#   - local: '.gitlab/job-rules.gitlab-ci.yml'

# Hidden base: reuse in other jobs if needed
.secret-analyzer:
  stage: scan
  interruptible: true
  image: "registry.gitlab.com/gitlab-org/security-products/analyzers/secrets:latest"
  services: []
  variables:
    GIT_DEPTH: "25"
    SECRET_DETECTION_EXCLUDED_PATHS: ""
    SECRET_DETECTION_IMAGE_SUFFIX: ""
    SECRETS_ANALYZER_VERSION: "latest"
    SECRET_DETECTION_HISTORIC_SCAN: "false"
    SECURE_ANALYZERS_FORCE_EXIT_CODE: "1"  # fail job on findings
  allow_failure: true
  script:
    - /analyzer run
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      secret_detection: gl-secret-detection-report.json

scan:secrets:
  extends: [".secret-analyzer"]
  rules: !reference [.rule:scan-on-mr-or-manual, rules]
