.secret-analyzer:
  variables:
    SECURE_ANALYZERS_PREFIX:       "$CI_TEMPLATE_REGISTRY_HOST/security-products"
    SECRET_DETECTION_IMAGE_SUFFIX: ""
    SECRETS_ANALYZER_VERSION:      "7"
    SECRET_DETECTION_EXCLUDED_PATHS: ""
  stage: scan
  image: "$SECURE_ANALYZERS_PREFIX/secrets:$SECRETS_ANALYZER_VERSION$SECRET_DETECTION_IMAGE_SUFFIX"
  services: []
  allow_failure: false
  artifacts:
    access: developer
    reports:
      secret_detection: gl-secret-detection-report.json
    paths:
      - gl-secret-detection-report.json

