# .gitlab/secrets.gitlab-ci.yml
include:
  - local: '.gitlab/job-rules.gitlab-ci.yml'  # must define .rule:scan-on-mr-to-env and .rule:scan-manual

# Hidden base: reuse in other jobs if needed
.secret-analyzer:
  stage: scan
  interruptible: true
  image: "registry.gitlab.com/gitlab-org/security-products/analyzers/secrets:latest"
  services: []
  variables:
    GIT_DEPTH: "25"
    SECRET_DETECTION_EXCLUDED_PATHS: ""
    SECRET_DETECTION_IMAGE_SUFFIX: ""
    SECRETS_ANALYZER_VERSION: "latest"
    SECRET_DETECTION_HISTORIC_SCAN: "false"
    SECURE_ANALYZERS_FORCE_EXIT_CODE: "1"  # fail job on findings
  allow_failure: false
  script:
    - /analyzer run
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      secret_detection: gl-secret-detection-report.json

# Turnkey job: runs automatically on MRs into dev|test|int|main
secrets_scan:
  extends: [".secret-analyzer"]
  rules: !reference [.rule:scan-on-mr-to-env, rules]

# Manual button: visible everywhere, never auto-runs
secrets_scan_manual:
  extends: [".secret-analyzer"]
  rules: !reference [.rule:scan-manual, rules]