secret-analyzer:
  stage: scan
  interruptible: true
  variables:
    CI_TEMPLATE_REGISTRY_HOST: "${CI_TEMPLATE_REGISTRY_HOST:-registry.gitlab.com/gitlab-org}"
    SECURE_ANALYZERS_PREFIX:   "$CI_TEMPLATE_REGISTRY_HOST/security-products/analyzers"
    SECRETS_ANALYZER_VERSION:  "7"
    SECRET_DETECTION_IMAGE_SUFFIX: ""
    SECRET_DETECTION_EXCLUDED_PATHS: ""
    SECRET_DETECTION_HISTORIC_SCAN: "false"
    SECURE_ANALYZERS_FORCE_EXIT_CODE: "1"
    GIT_DEPTH: "25"
  image: "$SECURE_ANALYZERS_PREFIX/secrets:$SECRETS_ANALYZER_VERSION$SECRET_DETECTION_IMAGE_SUFFIX"
  services: []
  allow_failure: false
  rules: !reference [.rule:scan-on-mr-to-env, rules]
  script:
    - /analyzer run
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      secret_detection: gl-secret-detection-report.json


secrets_scan_manual:
  extends: .secret-analyzer
  rules: !reference [.rule:scan-manual, rules]