.secret-analyzer:
  stage: scan
  interruptible: true
  image: "registry.gitlab.com/gitlab-org/security-products/analyzers/secrets:latest"
  services: []
  variables:
    SECRET_DETECTION_EXCLUDED_PATHS: ""
    SECRET_DETECTION_IMAGE_SUFFIX: ""
    SECRETS_ANALYZER_VERSION: "latest"
    GIT_DEPTH: "25"
  allow_failure: false
  rules: !reference [.rule:scan-on-mr-to-env, rules]
  script:
    - /analyzer run
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      secret_detection: gl-secret-detection-report.json


secrets_scan_manual:
  extends: .secret-analyzer
  rules: !reference [.rule:scan-manual, rules]