# .ci-templates/version-on-tag.yml
#
# How to use:
# 1. Include this template in your pipeline.
# 2. Add `needs: [release:version-from-tag]` in downstream jobs.
# 3. Use `$VERSION` as the tag for images or artifacts.

release:version:
  stage: release
  rules: !reference [.rule:tag-only, rules]

  variables:
    ENFORCE_SEMVER: "false"
    REQUIRE_PROTECTED_TAG: "false"

  before_script:
    - set -euo pipefail

  script:
    - |
      if [ -z "${CI_COMMIT_TAG:-}" ]; then
        echo "ERROR: Not running on a tag. Ref=${CI_COMMIT_REF_NAME}"; exit 1
      fi

    - |
      if [ "${REQUIRE_PROTECTED_TAG}" = "true" ] && [ "${CI_COMMIT_REF_PROTECTED:-false}" != "true" ]; then
        echo "ERROR: Tag '${CI_COMMIT_TAG}' is not protected."; exit 1
      fi

    - |
      if [ "${ENFORCE_SEMVER}" = "true" ]; then
        case "${CI_COMMIT_TAG}" in
          ([0-9]*.[0-9]*.[0-9]*|[0-9]*.[0-9]*.[0-9]*-*) : ;;
          (*) echo "ERROR: Tag '${CI_COMMIT_TAG}' is not SemVer"; exit 1 ;;
        esac
      fi

    - echo "${CI_COMMIT_TAG}" > VERSION
    - printf 'VERSION=%s\n' "${CI_COMMIT_TAG}" > version.env
    - echo "Set VERSION=${CI_COMMIT_TAG}"

  artifacts:
    expose_as: "VERSION"
    paths:
      - VERSION
    reports:
      dotenv: version.env
    when: always
    expire_in: 1 week
